/**
 * Produces the CMS audit: what is editable, and what is deliberately not.
 *
 *   node scripts/cms-audit.mjs
 *
 * Derived from the schema files and the built output rather than written by
 * hand, so it cannot quietly go out of date. Spec §24 asks for a checklist;
 * a checklist nobody can regenerate is a snapshot of what someone believed
 * once.
 */
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

const read = (p) => readFile(p, 'utf8');

/**
 * Top-level field names in a Sanity schema file, in order.
 *
 * Keyed off indentation rather than parsed: every schema file here is
 * Prettier-formatted, so a top-level `defineField` sits at four spaces and
 * anything nested inside an `of: [...]` sits deeper. That distinction is the
 * whole point — counting nested member names, group names and ordering names as
 * fields is what made the first version of this report claim `siteSettings` had
 * 58 fields.
 */
function fieldsOf(source) {
  return [...source.matchAll(/^ {4}defineField\(\{\s*\n? *name: '([a-zA-Z0-9_]+)'/gm)].map(
    (m) => m[1],
  );
}

function titleOf(source, fallback) {
  const m = /title:\s*'([^']+)'/.exec(source);
  return m ? m[1] : fallback;
}

const S = 'studio/schemaTypes';

const [docFiles, blockFiles, objFiles] = await Promise.all([
  readdir(`${S}/documents`),
  readdir(`${S}/blocks`),
  readdir(`${S}/objects`),
]);

const section = (name) => `\n## ${name}\n`;
const out = [];

out.push('# CMS audit');
out.push('');
out.push('Generated by `node scripts/cms-audit.mjs`. Every row is read from the');
out.push('schema files, so re-running it reflects whatever is actually there.');

out.push(section('Document types'));
out.push('| Type | Editable fields |');
out.push('| ---- | --------------- |');
for (const file of docFiles.filter((f) => f.endsWith('.ts')).sort()) {
  const src = await read(join(`${S}/documents`, file));
  const fields = fieldsOf(src);
  const readOnly = /readOnly:\s*true/.test(src) ? ' _(read-only)_' : '';
  out.push(
    `| \`${file.replace('.ts', '')}\`${readOnly} | ${fields.length}: ${fields.join(', ')} |`,
  );
}

out.push(section('Section blocks'));
out.push("Each maps to one component and appears in a page's Sections list.");
out.push('');
out.push('| Block | Editable fields |');
out.push('| ----- | --------------- |');
for (const file of blockFiles.filter((f) => f.endsWith('.ts') && !f.startsWith('_')).sort()) {
  const src = await read(join(`${S}/blocks`, file));
  const fields = fieldsOf(src).filter((f) => f !== 'hidden');
  out.push(
    `| ${titleOf(src, file)} | ${fields.length ? fields.join(', ') : '_visibility and order only_'} |`,
  );
}

out.push(section('Shared objects'));
out.push('| Object | Fields |');
out.push('| ------ | ------ |');
for (const file of objFiles.filter((f) => f.endsWith('.ts')).sort()) {
  const src = await read(join(`${S}/objects`, file));
  out.push(`| \`${file.replace('.ts', '')}\` | ${fieldsOf(src).join(', ')} |`);
}

out.push(section('Routes, and what drives each'));
const pages = await readdir('.vercel/output/static', { recursive: true }).catch(() => []);
const html = pages.filter((p) => typeof p === 'string' && p.endsWith('.html')).sort();
out.push('| Route | Driven by |');
out.push('| ----- | --------- |');
const driver = {
  'index.html': '`page` document `/` — 8 section blocks',
  'about/index.html': '`page` document `/about/`',
  'services/index.html': '`page` document `/services/`',
  'testimonials/index.html': '`page` document `/testimonials/`',
  'blog/index.html': '`page` document `/blog/`',
  'contact/index.html': '`page` document `/contact/`',
  '404.html': '`page` document `/404/`',
  'privacy-policy/index.html': 'Code, deliberately — see exceptions',
};
for (const p of html) {
  const key = p.replace(/\\/g, '/');
  const why = driver[key] ?? (key.startsWith('services/') ? '`service` document' : 'route file');
  out.push(`| \`/${key.replace(/index\.html$/, '')}\` | ${why} |`);
}

out.push(section('Deliberately not editable'));
out.push('Each of these is a decision with a reason, not a gap.');
out.push('');
out.push('| Item | Why |');
out.push('| ---- | --- |');
for (const [item, why] of [
  [
    '`SITE_URL` and `IS_PRODUCTION_HOST`',
    'Gate indexing. A content edit must not be able to deindex the site.',
  ],
  [
    'Robots "index this page" switch',
    'Only ever tightening is offered. The build decides indexability.',
  ],
  [
    'Calculator labels, ranges and maths',
    'A mislabelled rate field produces a figure a visitor might act on.',
  ],
  [
    'Privacy policy body',
    'Holding page whose prose reads live contact details from settings. Create a `page` document with that slug when the legal text arrives.',
  ],
  [
    'SMTP, reCAPTCHA secret, Sanity tokens, submission salt',
    'Credentials. Environment only, never in a document anyone with the dataset can read.',
  ],
  [
    'reCAPTCHA site key',
    'A matched pair with its secret. Splitting them across the CMS and the deployment lets them drift into a silent failure.',
  ],
  [
    'Colour, type scale, spacing, layout',
    'The design system. Named variants are offered where a section genuinely varies.',
  ],
  ['Footer column count', 'Three columns is the design. Making it arbitrary would be a redesign.'],
  [
    'Mobile navigation as a separate list',
    'It already renders the same nav. A second list that can diverge is a worse CMS.',
  ],
  [
    'Carousel arrow and slider `aria-label`s',
    'Accessibility plumbing for controls with no visible text.',
  ],
  ['Honeypot field label', 'Off-screen anti-spam field. Never seen.'],
  [
    'Post and service page templates',
    'Not block arrays, so not previewable either. Extracting them is the next step if page-builder control is wanted there.',
  ],
]) {
  out.push(`| ${item} | ${why} |`);
}

out.push('');
console.log(out.join('\n'));
